# Site settings
title: "Patrick Breheny"
baseurl: ""
url: "https://pbreheny.org"

# Build settings
markdown: kramdown
exclude: [pubs, Snakefile, software/*]

# SCSS settings
sass:
    style: compressed
