# Site settings
title: "Patrick Breheny"
baseurl: ""
url: "https://myweb.uiowa.edu/pbreheny"

# Build settings
markdown: kramdown
exclude: [build, background.R, pubs, data, dissertation, v, Makefile, software/*]

# SCSS settings
sass:
    style: compressed
